site_name: MyData Documentation
theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - navigation.path
  highlightjs: true
  hljs_languages:
    - rust
    - move
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
nav:
  - Home: index.md
  - Getting Started: GettingStarted.md
  - Developer Guide:
    - MyData Design: Design.md
    - Using MyData: UsingMyData.md
    - Access Policy Example Patterns: ExamplePatterns.md
    - Security Best Practices: SecurityBestPractices.md
  - Operator Guide:
    - Key Server Operations: KeyServerOps.md
    - Railway Deployment: RailwayDeployment.md
    - MyData CLI: MyDataCLI.md
  - Pricing: Pricing.md
  - Terms of Service: TermsOfService.md
