[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/opt/key-server/bin/key-server"
healthcheckPath = "/v1/service"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
RUST_LOG = "info"
RUST_BACKTRACE = "1"
CONFIG_PATH = "/app/config/key-server-config-railway.yaml"
MASTER_KEY = "0x9626290d5e30dea1e1d86a27086e64d4dc2955adbce4b6c54d6cd4fba015ac9c"

[[volumes]]
name = "config"
mountPath = "/app/config"

[[services]]
name = "mydata-key-server-2"
source = { repo = "https://github.com/The-Social-Proof-Foundation/myso-mydata", branch = "master" }

[services.variables]
PORT = "8080"
METRICS_PORT = "9184"
